# ***Numpy ndarray PRACTICE***

In [ ]:
array1 = np.arange(8)

''' PRACTICE

1. 1차원 array1 3차원 array3d 변환

[output]
array3d shape: (2, 2, 2)

2. 3차원 array3d 2차원 array2d 변환

[output]
array2d shape: (8, 1)

3. 1차원 array1를 2차원 array2d 변환

[output]
array2d shape: (4, 2)
'''
# 1차원 ndarray를 3차원 ndarray로 변환
array3d = array1.reshape((2,2,2))
print('array3d shape:\n',array3d.shape)

# 3차원 ndarray를 2차원 ndarray로 변환
array2d = array3d.reshape(-1,1)
print('array2d shape:',array2d.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array = array1.reshape(-1,2)
print('array shape:',array.shape)

# ***Numpy Indexing PRACTICE***

In [ ]:
'''1. 단일값 추출

[output]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
index 가리키는 값: 1
index 가리키는 값: 2
index 가리키는 값: 4
index 가리키는 값: 9

'''
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )


'''2. Slicing

[output]

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

(1)
array2d:
 [[1 2]
 [4 5]]

 (2)
array2d:
 [[2 3]
 [5 6]]

 (3)
array2d:
 [1 4]

# (3) array2d shape: (2,)
'''
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d: \n', array2d[:2, :2])
print('array2d: \n', array2d[:2, 1:])
print('array2d: \n', array2d[:2, 0])

# ***Numpy sort() PRACTICE***

In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

'''practice
[output]

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']

'''
sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])