#### Original ref : https://tutorials.pytorch.kr/beginner/basics/tensorqs_tutorial.html

In [1]:
%matplotlib inline

텐서(Tensor)
==========================================================================

텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조입니다.
PyTorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)합니다.

텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 `NumPy <https://numpy.org>`_ 의 ndarray와 유사합니다.
실제로 텐서와 NumPy 배열(array)은 종종 동일한 내부(underly) 메모리를 공유할 수 있어 데이터를 복수할 필요가 없습니다. (`bridge-to-np-label` 참고)
텐서는 또한 (`Autograd <autogradqs_tutorial.html>`__ 장에서 살펴볼) 자동 미분(automatic differentiation)에 최적화되어 있습니다.
ndarray에 익숙하다면 Tensor API를 바로 사용할 수 있을 것입니다. 아니라면, 아래 내용을 함께 보시죠!


In [2]:
import torch
import numpy as np

**텐서(tensor) 초기화**

텐서는 여러가지 방법으로 초기화할 수 있습니다. 다음 예를 살펴보세요:

**데이터로부터 직접(directly) 생성하기**

데이터로부터 직접 텐서를 생성할 수 있습니다. 데이터의 자료형(data type)은 자동으로 유추합니다.



In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

**NumPy 배열로부터 생성하기**

텐서는 NumPy 배열로 생성할 수 있습니다. (그 반대도 가능합니다 - `bridge-to-np-label` 참고)



In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**다른 텐서로부터 생성하기:**

명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지합니다.



In [5]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9032, 0.7482],
        [0.8027, 0.8354]]) 



**무작위(random) 또는 상수(constant) 값을 사용하기:**

``shape`` 은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 아래 함수들에서는 출력 텐서의 차원을 결정합니다.



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1488, 0.9217, 0.0460],
        [0.9335, 0.8278, 0.1767]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------




**텐서의 속성(Attribute)**

텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냅니다.



In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




**텐서 연산(Operation)**

전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수,
임의 샘플링(random sampling) 등, 100가지 이상의 텐서 연산들을
`여기 <https://pytorch.org/docs/stable/torch.html>` 에서 확인할 수 있습니다.

각 연산들은 (일반적으로 CPU보다 빠른) GPU에서 실행할 수 있습니다. Colab을 사용한다면,
Edit > Notebook Settings 에서 GPU를 할당할 수 있습니다.

기본적으로 텐서는 CPU에 생성됩니다. ``.to`` 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤)
GPU로 텐서를 명시적으로 이동할 수 있습니다. 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이
많이든다는 것을 기억하세요!



In [8]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

목록에서 몇몇 연산들을 시도해보세요.
NumPy API에 익숙하다면 Tensor API를 사용하는 것은 식은 죽 먹기라는 것을 알게 되실 겁니다.




**NumPy식의 표준 인덱싱과 슬라이싱:**



In [9]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**텐서 합치기** ``torch.cat`` 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있습니다.
``torch.cat`` 과 미묘하게 다른 또 다른 텐서 결합 연산인
`torch.stack <https://pytorch.org/docs/stable/generated/torch.stack.html>`__ 도 참고해보세요.



In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**산술 연산(Arithmetic operations)**



In [11]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**단일-요소(single-element) 텐서** 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우,
``item()`` 을 사용하여 Python 숫자 값으로 변환할 수 있습니다:



In [12]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**바꿔치기(in-place) 연산**
연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, ``_`` 접미사를 갖습니다.
예를 들어: ``x.copy_(y)`` 나 ``x.t_()`` 는 ``x`` 를 변경합니다.



In [13]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div class="alert alert-info"><h4>Note</h4><p>바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다.
     따라서, 사용을 권장하지 않습니다.</p></div>



--------------





**NumPy 변환(Bridge)**

CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.



텐서를 NumPy 배열로 변환하기



In [14]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 NumPy 배열에 반영됩니다.



In [15]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy 배열을 텐서로 변환하기



In [16]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy 배열의 변경 사항이 텐서에 반영됩니다.



In [17]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


--------------




# Practice

#### Q1. 모든 값이 1인 (32, 16) 크기의 행렬 mtx_1을 생성하시오.

In [ ]:
mtx_1 = torch.ones(size=(??, ??))
print(mtx_1)

#### Q2. 모든 값이 1인 (16, 8) 크기의 행렬 mtx_2을 생성하시오.

In [ ]:
mtx_2 = torch.ones(size=(??, ??))
print(mtx_2)

#### Q3. mtx_1 과 mtx_2 의 행렬곱을 수행하시오. (output : matmul_mtx)

In [ ]:
matmul_mtx = torch.??(mtx_1, mtx_2)
print(matmul_mtx)

#### Q4. matmul_mtx 의 shape 을 확인하시오.

In [ ]:
print(matmul_mtx.??)

In [59]:
# matmul_mtx 와 동일한 shape 의 random matrix 생성 (output : gaussian_mtx)
gaussian_mtx = torch.randn(matmul_mtx.shape)
print(gaussian_mtx)

tensor([[-7.0382e-01,  2.5474e+00,  1.2463e+00, -5.2671e-02,  4.0057e-01,
         -4.2897e-01,  7.7898e-01,  5.4074e-01],
        [ 6.2193e-01,  2.6354e+00, -1.5045e+00, -4.4965e-01,  4.0604e-01,
         -7.6350e-01,  3.0821e-01, -2.6210e-01],
        [-2.1576e-02, -8.8462e-02, -1.9312e+00, -8.0609e-01, -1.1919e+00,
         -1.0503e+00, -9.4545e-01,  1.3906e+00],
        [ 3.9474e-01,  6.8347e-01,  1.6193e+00,  5.7722e-03,  1.7203e+00,
         -4.7032e-01,  2.9673e-01, -7.8430e-01],
        [-1.0139e+00, -4.7480e-01,  3.0928e-01, -5.3794e-01, -9.6926e-02,
         -7.4104e-01,  6.5422e-02, -1.2768e+00],
        [ 1.0888e-01,  3.4596e-01, -8.8188e-01,  1.6153e-01, -1.3213e+00,
          6.4164e-01, -8.4240e-01, -4.5174e-02],
        [-2.7628e-01, -6.1614e-01,  1.2782e+00, -1.8571e+00,  1.0806e+00,
          7.2861e-01,  1.8707e+00,  1.4933e-01],
        [ 1.6187e+00,  1.3696e+00,  2.1633e+00,  5.5199e-01,  2.4198e-01,
          6.0378e-01,  8.5180e-01,  1.7929e+00],
        [-4.1931

In [60]:
# matmul_mtx 와 gaussian_mtx 을 더함 (output : mtx_3)
mtx_3 = torch.add(matmul_mtx, torch.randn(matmul_mtx.shape))
print(mtx_3)

tensor([[16.6285, 16.2179, 16.0773, 16.3773, 14.9458, 15.5663, 14.4950, 17.9996],
        [16.5090, 16.4590, 15.0642, 17.3271, 17.5866, 17.1456, 16.5718, 16.1092],
        [14.9058, 16.8461, 17.6556, 15.9130, 15.0966, 15.3434, 16.1445, 15.8529],
        [15.7383, 16.7165, 14.3049, 15.4195, 15.2214, 17.1195, 16.2669, 16.4199],
        [16.1487, 14.1199, 14.4108, 15.2979, 16.2906, 15.4998, 15.3860, 17.3450],
        [15.2825, 14.9088, 17.0454, 16.6508, 17.2701, 15.6978, 17.9011, 14.7983],
        [15.1025, 15.6425, 14.7540, 16.6029, 17.4210, 17.6045, 15.8402, 16.1634],
        [14.8950, 15.9988, 16.2832, 15.5265, 15.1750, 16.8770, 16.4692, 16.4911],
        [16.9773, 15.4633, 14.2659, 15.5330, 16.2453, 16.2045, 15.5951, 16.0120],
        [15.9120, 15.6839, 16.2399, 14.3839, 15.4428, 16.6298, 16.3478, 16.9176],
        [16.2110, 15.8901, 17.1357, 15.9681, 16.9194, 15.2816, 16.3997, 14.6482],
        [14.9637, 15.3813, 15.6100, 15.9564, 15.9547, 17.1286, 19.5321, 17.0413],
        [16.6763

In [61]:
# mtx_3 내 모든 value 들의 평균 구하기
print(torch.mean(mtx_3))

tensor(15.9630)


In [45]:
# mtx_3 내 column 기준 평균 구하기 (dim=0)
torch.mean(mtx_3, dim=0)

tensor([16.0597, 15.9245, 15.8284, 16.0833, 16.1269, 16.0282, 15.9445, 15.9621])

In [62]:
# mtx_3 내 row 기준 평균 구하기 (dim=1)
torch.mean(mtx_3, dim=1)

tensor([16.0385, 16.5966, 15.9698, 15.9009, 15.5623, 16.1944, 16.1414, 15.9645,
        15.7871, 15.9447, 16.0567, 16.4460, 15.9970, 16.3199, 16.5706, 15.8939,
        15.4142, 16.1754, 15.9514, 15.8984, 16.2157, 15.6320, 15.4141, 16.2407,
        15.8202, 15.5783, 15.9149, 15.4273, 16.3331, 15.7955, 15.7912, 15.8292])